### ISSUE TITLE
Moreland scraper

### ISSUE THREAD

**Issue by TJC** [openaustralia/planningalerts-parsers#1]
Hi,
I live in the LGA area of Moreland, in Victoria.
It encompasses such suburbs as Brunswick, Coburg, Pascoe Vale, Glenroy and Fawkner.

I'd like to write a scraper for the area, as I can't see one here at the moment. However I notice that if I search for an address in Brunswick, results do come back.
Does this mean someone has already written one?

My previous experience with writing scrapers includes ones that scrape the REIV and realestate.com.au websites.

Thanks,
Toby

**Comment by TJC** [comment]
I note that the things there are all more than six months out of date though. Hmm..

**Comment by henare** [comment]
> I'd like to write a scraper for the area, as I can't see one here at the moment. However I notice that if I search for an address in Brunswick, results do come back.
> Does this mean someone has already written one?

Hi Toby, that's brilliant, it'd be great if you could write a scraper for Moreland.

Currently we [only cover](http://www.planningalerts.org.au/about#vic) applications for Moreland lodged via [SPEAR](http://www.spear.land.vic.gov.au/spear/publicSearch/Search.do) so that's why you're seeing results for Brunswick.

We've been writing new scrapers using [ScraperWiki](http://scraperwiki.com/tags/planningalerts) which allows you to write scrapers in Ruby, Python and PHP.

I recently started [a guide to writing scrapers](https://docs.google.com/document/d/1K7oH1K7dj-foimRuhfCgr_XXSkhFMhmV6H_f-55bBag/edit?hl=en_GB) so please check that and do not hesitate to message me if you have any questions.

Looking forward to seeing your Moreland scraper!

Cheers,

Henare

**Comment by henare** [comment]
> I note that the things there are all more than six months out of date though. Hmm..

I thought the [SPEAR scraper](http://www.planningalerts.org.au/authorities/moreland/applications) might be broken but it doesn't look like it; it's just that there haven't been any in Brunswick via SPEAR for a while I guess.

**Comment by TJC** [comment]
Hmm, there's quite a few available by the Moreland Council site:
https://eservices.moreland.vic.gov.au/ePathway/Production/Web/GeneralEnquiry/EnquirySummaryView.aspx

I'll get onto it shortly..Thanks for the link to the guide.

**Comment by henare** [comment]
Not a problem. The guide is very ScraperWiki-centric but you certainly don't have to use it if you'd rather write a scraper in say, Perl :) You just have to spit out XML in the right format.

**Comment by TJC** [comment]
OK, my parser it dumping stuff like the following currently.. Does this look about right to you?

http://pastebin.com/vjDDUr3C

At the moment I'm just grabbing the "advertised planning permits", rather than the "decisions on planning permits" or other stuff like that.. (See options available at https://eservices.moreland.vic.gov.au/ePathway/Production/Web/GeneralEnquiry/EnquiryLists.aspx

**Comment by henare** [comment]
> OK, my parser it dumping stuff like the following currently.. Does this look about right to you?

Looking good!

You're probably planning it but 'description' is another important field you can get on their pages.

Another point is that when you visit the links in 'info_url' in a fresh browser their website throws an error. Whilst you've technically got the correct data there, for the user experience it's better to just set 'info_url' to the [front page](https://eservices.moreland.vic.gov.au/ePathway/Production/Web/GeneralEnquiry/EnquiryLists.aspx) so that when a user clicks on a more info link they're not presented with an error message.

> At the moment I'm just grabbing the "advertised planning permits", rather than the "decisions on planning permits" or other stuff like that.. (See options available at https://eservices.moreland.vic.gov.au/ePathway/Production/Web/GeneralEnquiry/EnquiryLists.aspx

I agree; the best one to get is 'Planning permit applications advertised' as that's the most important data to PlanningAlerts users.

**Comment by TJC** [comment]
Whoops.. I am retrieving the description, but wasn't putting it into the XML! Fixed now.
Also fixed the INFO URL.
Should I put the same general enquiry URL into the comment url as well?

**Comment by TJC** [comment]
Actually, there is no way to comment from that enquiry page.. I can't seem to find a way via the rest of their site either!

**Comment by TJC** [comment]
Current XML: http://pastebin.com/2xJ4bG1x

**Comment by henare** [comment]
XML looking good.

Yeah, I had no luck finding out how to comment on a DA. Often councils will have an email address to send to but I can't find that either. It might be worth just calling them and asking what email address you should send a response to.

**Comment by TJC** [comment]
OK, my scraper is here:

https://github.com/TJC/Moreland-Scraper

To install it:

perl Makefile.PL
make
make install
(there are no tests)
(it will prompt you to install dependencies if they are missing)

It's pretty quick and dirty, but should be reliable enough unless they change their page lay-out too much.

Let me know if you'd like any changes made.

**Comment by henare** [comment]
Thanks, I've now added your scraper to our repository and deployed it.

If you'd like to help out with any more :) Don't hesitate to contact us on our [mailing list](http://groups.google.com/group/openaustralia-dev) or log bugs on our [issue tracker](http://tickets.openaustraliafoundation.org.au/).

Thanks again!
